### ISSUE TITLE
I can't die, I can't kill, I can't escape

### ISSUE THREAD

**Issue by jangisaac-dev** [stayintarkov/SIT.Manager.Avalonia#291]
I'm using the latest version.

Even though the gameplay works normally,
Neither the scavs nor the scavs die when they engage.
The hp doesn't wear out.

Even escape is impossible, and items are retained when out through esc.

What did I do wrong?
I installed it correctly as instructed by the document.

--in linux docker server
```
2024-05-26 19:42:34 Error: incorrect header check
2024-05-26 19:42:34 Error: incorrect header check
2024-05-26 19:42:34     at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
2024-05-26 19:42:34     at processChunkSync (node:zlib:457:12)
2024-05-26 19:42:34     at zlibBufferSync (node:zlib:178:12)
2024-05-26 19:42:34     at Object.inflateSync (node:zlib:809:14)
2024-05-26 19:42:34     at IncomingMessage.<anonymous> (/snapshot/src/servers/http/AkiHttpListener.ts:69:60)
2024-05-26 19:42:34     at IncomingMessage.emit (node:events:518:28)
2024-05-26 19:42:34     at endReadableNT (node:internal/streams/readable:1696:12)
2024-05-26 19:42:34     at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-05-26 19:42:34 Error: incorrect header check
2024-05-26 19:42:34 Error: incorrect header check
2024-05-26 19:42:34     at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
2024-05-26 19:42:34     at processChunkSync (node:zlib:457:12)
2024-05-26 19:42:34     at zlibBufferSync (node:zlib:178:12)
2024-05-26 19:42:34     at Object.inflateSync (node:zlib:809:14)
2024-05-26 19:42:34     at IncomingMessage.<anonymous> (/snapshot/src/servers/http/AkiHttpListener.ts:69:60)
2024-05-26 19:42:34     at IncomingMessage.emit (node:events:518:28)
2024-05-26 19:42:34     at endReadableNT (node:internal/streams/readable:1696:12)
2024-05-26 19:42:34     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

--in client command screen log
```Parameter name: source
[Exception] : ArgumentNullException: Value cannot be null.
System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
StayInTarkov.Coop.Player.InteractionPatches.Player_StartDoorInteraction_Patch.Replicated (EFT.Player player, System.Collections.Generic.Dictionary`2[TKey,TValue] dict) (at <d8b27bfcc1714cb3882059e2202d37d7>:0)
StayInTarkov.Core.Player.PlayerReplicatedComponent.ProcessPacket (System.Collections.Generic.Dictionary`2[TKey,TValue] packet) (at <d8b27bfcc1714cb3882059e2202d37d7>:0)
StayInTarkov.Coop.Components.ActionPacketHandlerComponent.ProcessPlayerPacket (System.Collections.Generic.Dictionary`2[TKey,TValue] packet) (at <d8b27bfcc1714cb3882059e2202d37d7>:0)
StayInTarkov.Coop.Components.ActionPacketHandlerComponent.ProcessLastActionDataPacket (System.Collections.Generic.Dictionary`2[TKey,TValue] packet) (at <d8b27bfcc1714cb3882059e2202d37d7>:0)
StayInTarkov.Coop.Components.ActionPacketHandlerComponent.ProcessActionPackets () (at <d8b27bfcc1714cb3882059e2202d37d7>:0)
StayInTarkov.Coop.Components.ActionPacketHandlerComponent.LateUpdate () (at <d8b27bfcc1714cb3882059e2202d37d7>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
LogHandler:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)```

**Comment by artehe** [comment]
The most likely reason is one of the ports required isn't open.

However I'm closing this as it's not related to the manager, you can find better help in [discord](https://stayintarkov.com/discord)
